[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

lib_deps = 
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/DHT sensor library@^1.4.6

upload_port = COM10
upload_speed = 115200
upload_protocol = esptool
monitor_speed = 115200
